/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.Conexion;
import CapaLogica.FuncionesEstudiantes;
import CapaLogica.ManejadorImagenes;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class AgregarReCon extends javax.swing.JFrame {

    /**
     * Creates new form AgregarReCon
     */
    public AgregarReCon() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelConsulta = new javax.swing.JPanel();
        jLabelRegistar1 = new javax.swing.JLabel();
        jLCodigo1 = new javax.swing.JLabel();
        jLNombre1 = new javax.swing.JLabel();
        jLSexo1 = new javax.swing.JLabel();
        txtIdEstudiante = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        jLabelNotaEditar = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanelEditar = new javax.swing.JPanel();
        jLabelRegistar3 = new javax.swing.JLabel();
        jLCodigo3 = new javax.swing.JLabel();
        jLNombre3 = new javax.swing.JLabel();
        jLSexo3 = new javax.swing.JLabel();
        jLPrograma3 = new javax.swing.JLabel();
        jTFCodigo3 = new javax.swing.JTextField();
        jTFNombre3 = new javax.swing.JTextField();
        jCBSexo3 = new javax.swing.JComboBox();
        jCBPrograma3 = new javax.swing.JComboBox();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelRegistar = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLSexo = new javax.swing.JLabel();
        jLPrograma = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jCBSexo = new javax.swing.JComboBox();
        jButtonLimpiarR = new javax.swing.JButton();
        jButtonRegistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLPrograma1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        CmbSeccion = new javax.swing.JComboBox<>();
        CmbGrado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CbnCurso = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnEstudiatesFrm = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRepotes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelRegistar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelConsulta.setLayout(null);

        jLabelRegistar1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar1.setText("Consulta Estudiantes");
        jPanelConsulta.add(jLabelRegistar1);
        jLabelRegistar1.setBounds(0, 10, 580, 40);

        jLCodigo1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLCodigo1.setText("Codigo");
        jPanelConsulta.add(jLCodigo1);
        jLCodigo1.setBounds(20, 70, 180, 30);

        jLNombre1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLNombre1.setText("Nombre");
        jPanelConsulta.add(jLNombre1);
        jLNombre1.setBounds(20, 110, 180, 30);

        jLSexo1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLSexo1.setText("Sexo");
        jPanelConsulta.add(jLSexo1);
        jLSexo1.setBounds(20, 150, 180, 30);
        jPanelConsulta.add(txtIdEstudiante);
        txtIdEstudiante.setBounds(200, 70, 200, 30);
        jPanelConsulta.add(txtNombre);
        txtNombre.setBounds(200, 110, 200, 30);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanelConsulta.add(cmbSexo);
        cmbSexo.setBounds(200, 150, 200, 30);

        btnEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanelConsulta.add(btnEliminar);
        btnEliminar.setBounds(420, 140, 140, 35);

        btnConsultar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanelConsulta.add(btnConsultar);
        btnConsultar.setBounds(420, 60, 140, 35);

        btnEditar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEditar.setText("EDITAR*");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanelConsulta.add(btnEditar);
        btnEditar.setBounds(420, 100, 140, 35);

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Fecha Nacimiento", "Sexo", "Grado", "Seccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaResultados);

        jPanelConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(20, 250, 540, 140);

        jLabelNotaEditar.setText("* Debe seleccionar solamente una fila dentro de la tabla");
        jPanelConsulta.add(jLabelNotaEditar);
        jLabelNotaEditar.setBounds(20, 392, 540, 15);

        jButton5.setText("LIMPIAR TODO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelConsulta.add(jButton5);
        jButton5.setBounds(420, 190, 140, 30);

        jTabbedPane1.addTab("Consultar", jPanelConsulta);

        jPanelEditar.setLayout(null);

        jLabelRegistar3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar3.setText("Edicion Estudiante");
        jPanelEditar.add(jLabelRegistar3);
        jLabelRegistar3.setBounds(0, 10, 580, 40);

        jLCodigo3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLCodigo3.setText("Codigo");
        jPanelEditar.add(jLCodigo3);
        jLCodigo3.setBounds(50, 70, 200, 30);

        jLNombre3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLNombre3.setText("Nombre");
        jPanelEditar.add(jLNombre3);
        jLNombre3.setBounds(50, 110, 200, 30);

        jLSexo3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLSexo3.setText("Sexo");
        jPanelEditar.add(jLSexo3);
        jLSexo3.setBounds(50, 150, 200, 30);

        jLPrograma3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLPrograma3.setText("Codigo Programa");
        jPanelEditar.add(jLPrograma3);
        jLPrograma3.setBounds(50, 190, 200, 30);

        jTFCodigo3.setEditable(false);
        jTFCodigo3.setEnabled(false);
        jPanelEditar.add(jTFCodigo3);
        jTFCodigo3.setBounds(260, 70, 250, 30);

        jTFNombre3.setEditable(false);
        jPanelEditar.add(jTFNombre3);
        jTFNombre3.setBounds(260, 110, 250, 30);

        jCBSexo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Masculino", "Femenino" }));
        jPanelEditar.add(jCBSexo3);
        jCBSexo3.setBounds(260, 150, 250, 30);

        jCBPrograma3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jCBPrograma3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBPrograma3PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanelEditar.add(jCBPrograma3);
        jCBPrograma3.setBounds(260, 190, 250, 30);

        jTabbedPane1.addTab("Editar", jPanelEditar);

        jPanelRegistro.setLayout(null);

        jLabelRegistar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar.setText("Registar Estudiante");
        jPanelRegistro.add(jLabelRegistar);
        jLabelRegistar.setBounds(0, 10, 580, 40);

        jLCodigo.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLCodigo.setText("Codigo");
        jPanelRegistro.add(jLCodigo);
        jLCodigo.setBounds(50, 70, 200, 30);

        jLNombre.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLNombre.setText("Nombre");
        jPanelRegistro.add(jLNombre);
        jLNombre.setBounds(50, 110, 200, 30);

        jLSexo.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLSexo.setText("Sexo");
        jPanelRegistro.add(jLSexo);
        jLSexo.setBounds(50, 150, 200, 30);

        jLPrograma.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLPrograma.setText("Seccion");
        jPanelRegistro.add(jLPrograma);
        jLPrograma.setBounds(40, 310, 200, 30);
        jPanelRegistro.add(txtId);
        txtId.setBounds(260, 70, 250, 30);

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanelRegistro.add(jCBSexo);
        jCBSexo.setBounds(260, 150, 250, 30);

        jButtonLimpiarR.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonLimpiarR.setText("LIMPIAR");
        jButtonLimpiarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarRActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonLimpiarR);
        jButtonLimpiarR.setBounds(310, 410, 180, 35);

        jButtonRegistar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonRegistar.setText("REGISTAR");
        jButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonRegistar);
        jButtonRegistar.setBounds(120, 410, 170, 35);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Apellido");
        jPanelRegistro.add(jLabel2);
        jLabel2.setBounds(50, 190, 80, 30);
        jPanelRegistro.add(TxtNombre);
        TxtNombre.setBounds(260, 110, 250, 30);
        jPanelRegistro.add(txtFecha);
        txtFecha.setBounds(260, 230, 250, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nacimiento");
        jPanelRegistro.add(jLabel3);
        jLabel3.setBounds(50, 230, 180, 30);

        jLPrograma1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLPrograma1.setText("Grado");
        jPanelRegistro.add(jLPrograma1);
        jLPrograma1.setBounds(50, 270, 200, 30);
        jPanelRegistro.add(txtApellido);
        txtApellido.setBounds(260, 190, 250, 30);

        CmbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion A", "Seccion B" }));
        jPanelRegistro.add(CmbSeccion);
        CmbSeccion.setBounds(260, 310, 240, 30);

        CmbGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo" }));
        jPanelRegistro.add(CmbGrado);
        CmbGrado.setBounds(260, 270, 240, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Cursos");
        jPanelRegistro.add(jLabel4);
        jLabel4.setBounds(70, 360, 90, 20);

        CbnCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematicas", "Comunicacion", "Programacion", "base de datos", "Lenguaje" }));
        jPanelRegistro.add(CbnCurso);
        CbnCurso.setBounds(270, 360, 240, 30);

        jTabbedPane1.addTab("Registar", jPanelRegistro);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Universidad Mariano 3.jpg"))); // NOI18N

        BtnEstudiatesFrm.setText("Estudiantes");
        BtnEstudiatesFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstudiatesFrmActionPerformed(evt);
            }
        });

        jButton3.setText("Catedratico");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnRepotes.setText("Repostes");
        btnRepotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepotesActionPerformed(evt);
            }
        });

        jButton1.setText("Cursos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnRepotes)
                    .addComponent(jButton3)
                    .addComponent(BtnEstudiatesFrm)
                    .addComponent(jLabel1))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(BtnEstudiatesFrm)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(btnRepotes)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jLabelRegistar2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar2.setText("Gestion Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegistar2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();

        // Obtener la fila seleccionada
        int filaSeleccionada = TablaResultados.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Obtener el valor de la primera columna en la fila seleccionada (suponiendo que es el ID)
            int idEstudiante = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());

            // Crear una instancia de FuncionesEstudiantes y llamar al método eliminarEstudiante
            FuncionesEstudiantes funcionesEstudiantes = new FuncionesEstudiantes();
            funcionesEstudiantes.eliminarEstudiante(idEstudiante, modelo);

            // Eliminar la fila de la tabla
            modelo.removeRow(filaSeleccionada);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Crear una instancia de FuncionesEstudiantes
        FuncionesEstudiantes funcionesEstudiantes = new FuncionesEstudiantes();

        // Obtener el id_estudiante desde algún componente de la interfaz (por ejemplo, un JTextField)
        int id_estudiante = Integer.parseInt(txtIdEstudiante.getText());

        // Llamar al método buscarEstudiantePorId y pasar el modelo de la tabla
        funcionesEstudiantes.buscarEstudiantePorId((DefaultTableModel) TablaResultados.getModel(), id_estudiante);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();
        FuncionesEstudiantes estudiantes = new FuncionesEstudiantes();
        // Obtener la fila seleccionada
        int filaSeleccionada = TablaResultados.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas en la fila seleccionada
            Object id = modelo.getValueAt(filaSeleccionada, 0);

            // Obtener los nuevos valores de los campos de texto y combobox
            String nuevoNombre = txtNombre.getText();
            String nuevoId = txtIdEstudiante.getText();
            String nuevoSexo = cmbSexo.getSelectedItem().toString();

            // Actualizar la información en la base de datos
            actualizarInformacionEstudiante(Integer.parseInt(id.toString()), nuevoNombre, nuevoId, nuevoSexo);

            // Limpiar la tabla y volver a cargar los datos
            estudiantes.limpiarTabla(modelo);
            // Vuelve a cargar todos los datos en la tabla (puedes llamar a tu método que carga los datos aquí)
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    private void actualizarInformacionEstudiante(int idEstudiante, String nuevoNombre, String nuevoId, String nuevoSexo) {
        Conexion db = new Conexion();

        try {
            Connection cn = db.getConnection();
            String consultaSQL = "UPDATE estudiantes SET nombre=?, id_estudiante=?, sexo=? WHERE id_estudiante=?";
            PreparedStatement pst = cn.prepareStatement(consultaSQL);

            pst.setString(1, nuevoNombre);
            pst.setString(2, nuevoId);
            pst.setString(3, nuevoSexo);
            pst.setInt(4, idEstudiante);

            int filasActualizadas = pst.executeUpdate();

            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(null, "Estudiante actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la información del estudiante.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar la información del estudiante: " + e);
        } finally {
            db.close(); // Cerrar la conexión al finalizar
        }
    }
    private void jCBPrograma3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBPrograma3PopupMenuWillBecomeVisible

    }//GEN-LAST:event_jCBPrograma3PopupMenuWillBecomeVisible

    private void jButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarActionPerformed
        // Obtener los valores de los campos de texto y combobox
        String id = txtId.getText();
        String nombre = TxtNombre.getText();
        String apellido = txtApellido.getText();
        String sexo = cmbSexo.getSelectedItem().toString();
        String fechaNacimiento = txtFecha.getText();  // Asumiendo que txtFecha es un campo de texto para la fecha

        // Imprime los valores para depuración
        System.out.println("ID: " + id);
        System.out.println("Nombre: " + nombre);
        System.out.println("Apellido: " + apellido);
        System.out.println("Sexo: " + sexo);
        System.out.println("Fecha de Nacimiento: " + fechaNacimiento);
        String grado = CmbGrado.getSelectedItem().toString();
        String seccion = CmbSeccion.getSelectedItem().toString();
        String cursoSeleccionado = CbnCurso.getSelectedItem().toString();
        System.out.println("Grado: " + grado);
        System.out.println("Sección: " + seccion);
        System.out.println("Curso: " + cursoSeleccionado);

        // Guardar la información en la base de datos
        // Limpiar los campos después de guardar
        limpiarCampos();
        JFileChooser fileChooser = new JFileChooser(); // cosntructor que ejecuta el Jfilechoser que es un metodo que abre una ventana para buscar una imagen
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String rutaImagen = selectedFile.getAbsolutePath();

            // Imprime la ruta para depuración
            System.out.println("Ruta de la imagen: " + rutaImagen);

            // Ahora, llama al método que guarda la información y la imagen
            guardarEstudianteConImagen(id, nombre, apellido, sexo, fechaNacimiento, rutaImagen, grado, seccion, cursoSeleccionado);
        }
    }//GEN-LAST:event_jButtonRegistarActionPerformed
    private void guardarEstudianteConImagen(String id, String nombre, String apellido, String sexo, String fechaNacimiento, String rutaImagen, String grado, String seccion, String cursoSeleccionado) {
        Conexion db = new Conexion();

        try {
            Connection cn = db.getConnection();
            String consultaSQL = "INSERT INTO estudiantes (id_estudiante, nombre, apellidos, sexo, fecha_nacimiento, imagen, grado, seccion, cursos) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = cn.prepareStatement(consultaSQL);

            // Código existente para la información del estudiante
            pst.setString(1, id);
            pst.setString(2, nombre);
            pst.setString(3, apellido);
            pst.setString(4, sexo);
            pst.setString(5, fechaNacimiento);
            pst.setString(7, grado);
            pst.setString(8, seccion);
            pst.setString(9, cursoSeleccionado);
            ManejadorImagenes manejadorImagenes = new ManejadorImagenes();
            // Cargar la imagen como bytes
            byte[] imagenBytes = manejadorImagenes.leerImagenComoBytes(rutaImagen);
            pst.setBytes(6, imagenBytes);

            int filasInsertadas = pst.executeUpdate();

            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(null, "Estudiante registrado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el estudiante.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al registrar el estudiante: " + e.getMessage());
        } finally {
            db.close();
        }
    }

    private void limpiarCampos() {
        // Limpiar los campos de texto y combobox
        txtId.setText("");
        TxtNombre.setText("");
        txtApellido.setText("");
        cmbSexo.setSelectedIndex(0);  // Puedes ajustar esto según la posición de las opciones en tu combobox
        txtFecha.setText("");
        CbnCurso.setSelectedItem(0);
    }

    private void limpiarConsultas() {
        txtIdEstudiante.setText("");
        txtNombre.setText("");
    }

    private void jButtonLimpiarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarRActionPerformed

    }//GEN-LAST:event_jButtonLimpiarRActionPerformed

    private void BtnEstudiatesFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstudiatesFrmActionPerformed
        Estudiante e = new Estudiante();
        e.setVisible(true);
        dispose();

    }//GEN-LAST:event_BtnEstudiatesFrmActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Catedratico c = new Catedratico();
        c.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void TablaResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaResultadosMouseClicked

        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();

        // Obtener la fila seleccionada
        int filaSeleccionada = TablaResultados.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas en la fila seleccionada
            Object id = modelo.getValueAt(filaSeleccionada, 0);
            Object nombre = modelo.getValueAt(filaSeleccionada, 1);
            Object sexo = modelo.getValueAt(filaSeleccionada, 2);

            // Asignar los valores a los campos de texto y combobox
            txtIdEstudiante.setText(id.toString());
            txtNombre.setText(nombre.toString());
            cmbSexo.setSelectedItem(sexo.toString());


        }    }//GEN-LAST:event_TablaResultadosMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Crear una instancia de FuncionesEstudiantes
        FuncionesEstudiantes funcionesEstudiantes = new FuncionesEstudiantes();

        // Llamar al método limpiarTabla y pasar el modelo de la tabla
        funcionesEstudiantes.limpiarTabla((DefaultTableModel) TablaResultados.getModel());

        limpiarConsultas();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnRepotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepotesActionPerformed

        Reportes r = new Reportes();
        r.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnRepotesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Cursos c = new Cursos();
        c.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEstudiatesFrm;
    private javax.swing.JComboBox<String> CbnCurso;
    private javax.swing.JComboBox<String> CmbGrado;
    private javax.swing.JComboBox<String> CmbSeccion;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRepotes;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonLimpiarR;
    private javax.swing.JButton jButtonRegistar;
    private javax.swing.JComboBox jCBPrograma3;
    private javax.swing.JComboBox jCBSexo;
    private javax.swing.JComboBox jCBSexo3;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLCodigo1;
    private javax.swing.JLabel jLCodigo3;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLNombre3;
    private javax.swing.JLabel jLPrograma;
    private javax.swing.JLabel jLPrograma1;
    private javax.swing.JLabel jLPrograma3;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLSexo1;
    private javax.swing.JLabel jLSexo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNotaEditar;
    private javax.swing.JLabel jLabelRegistar;
    private javax.swing.JLabel jLabelRegistar1;
    private javax.swing.JLabel jLabelRegistar2;
    private javax.swing.JLabel jLabelRegistar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo3;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEstudiante;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
