/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.Conexion;
import CapaLogica.FuncionesEstudiantes;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hetzo
 */
public class AgregarReCon extends javax.swing.JFrame {

    /**
     * Creates new form AgregarReCon
     */
    public AgregarReCon() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelConsulta = new javax.swing.JPanel();
        jLabelRegistar1 = new javax.swing.JLabel();
        jLCodigo1 = new javax.swing.JLabel();
        jLNombre1 = new javax.swing.JLabel();
        jLSexo1 = new javax.swing.JLabel();
        jLPrograma1 = new javax.swing.JLabel();
        txtIdEstudiante = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        jCBPrograma1 = new javax.swing.JComboBox();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        jLabelNotaEditar = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanelEditar = new javax.swing.JPanel();
        jLabelRegistar3 = new javax.swing.JLabel();
        jLCodigo3 = new javax.swing.JLabel();
        jLNombre3 = new javax.swing.JLabel();
        jLSexo3 = new javax.swing.JLabel();
        jLPrograma3 = new javax.swing.JLabel();
        jTFCodigo3 = new javax.swing.JTextField();
        jTFNombre3 = new javax.swing.JTextField();
        jCBSexo3 = new javax.swing.JComboBox();
        jCBPrograma3 = new javax.swing.JComboBox();
        jButtonLimpiarE = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jLabelRegistar = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLSexo = new javax.swing.JLabel();
        jLPrograma = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jCBSexo = new javax.swing.JComboBox();
        jCBPrograma = new javax.swing.JComboBox();
        jButtonLimpiarR = new javax.swing.JButton();
        jButtonRegistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelRegistar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelConsulta.setLayout(null);

        jLabelRegistar1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar1.setText("Consulta Estudiantes");
        jPanelConsulta.add(jLabelRegistar1);
        jLabelRegistar1.setBounds(0, 10, 580, 40);

        jLCodigo1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLCodigo1.setText("Codigo");
        jPanelConsulta.add(jLCodigo1);
        jLCodigo1.setBounds(20, 70, 180, 30);

        jLNombre1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLNombre1.setText("Nombre");
        jPanelConsulta.add(jLNombre1);
        jLNombre1.setBounds(20, 110, 180, 30);

        jLSexo1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLSexo1.setText("Sexo");
        jPanelConsulta.add(jLSexo1);
        jLSexo1.setBounds(20, 150, 180, 30);

        jLPrograma1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLPrograma1.setText("Codigo Programa");
        jPanelConsulta.add(jLPrograma1);
        jLPrograma1.setBounds(20, 190, 180, 30);
        jPanelConsulta.add(txtIdEstudiante);
        txtIdEstudiante.setBounds(200, 70, 200, 30);
        jPanelConsulta.add(txtNombre);
        txtNombre.setBounds(200, 110, 200, 30);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanelConsulta.add(cmbSexo);
        cmbSexo.setBounds(200, 150, 200, 30);

        jCBPrograma1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jCBPrograma1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBPrograma1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanelConsulta.add(jCBPrograma1);
        jCBPrograma1.setBounds(200, 190, 200, 30);

        btnEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanelConsulta.add(btnEliminar);
        btnEliminar.setBounds(420, 140, 140, 35);

        btnConsultar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanelConsulta.add(btnConsultar);
        btnConsultar.setBounds(420, 60, 140, 35);

        btnEditar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEditar.setText("EDITAR*");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanelConsulta.add(btnEditar);
        btnEditar.setBounds(420, 100, 140, 35);

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Fecha Nacimiento", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaResultados);

        jPanelConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(20, 250, 540, 140);

        jLabelNotaEditar.setText("* Debe seleccionar solamente una fila dentro de la tabla");
        jPanelConsulta.add(jLabelNotaEditar);
        jLabelNotaEditar.setBounds(20, 392, 540, 15);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton4.setText("LIMPIAR TABLA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelConsulta.add(jButton4);
        jButton4.setBounds(420, 180, 140, 40);

        jTabbedPane1.addTab("Consultar", jPanelConsulta);

        jPanelEditar.setLayout(null);

        jLabelRegistar3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar3.setText("Edicion Estudiante");
        jPanelEditar.add(jLabelRegistar3);
        jLabelRegistar3.setBounds(0, 10, 580, 40);

        jLCodigo3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLCodigo3.setText("Codigo");
        jPanelEditar.add(jLCodigo3);
        jLCodigo3.setBounds(50, 70, 200, 30);

        jLNombre3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLNombre3.setText("Nombre");
        jPanelEditar.add(jLNombre3);
        jLNombre3.setBounds(50, 110, 200, 30);

        jLSexo3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLSexo3.setText("Sexo");
        jPanelEditar.add(jLSexo3);
        jLSexo3.setBounds(50, 150, 200, 30);

        jLPrograma3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLPrograma3.setText("Codigo Programa");
        jPanelEditar.add(jLPrograma3);
        jLPrograma3.setBounds(50, 190, 200, 30);

        jTFCodigo3.setEnabled(false);
        jPanelEditar.add(jTFCodigo3);
        jTFCodigo3.setBounds(260, 70, 250, 30);
        jPanelEditar.add(jTFNombre3);
        jTFNombre3.setBounds(260, 110, 250, 30);

        jCBSexo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Masculino", "Femenino" }));
        jPanelEditar.add(jCBSexo3);
        jCBSexo3.setBounds(260, 150, 250, 30);

        jCBPrograma3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jCBPrograma3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBPrograma3PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanelEditar.add(jCBPrograma3);
        jCBPrograma3.setBounds(260, 190, 250, 30);

        jButtonLimpiarE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonLimpiarE.setText("LIMPIAR");
        jButtonLimpiarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarEActionPerformed(evt);
            }
        });
        jPanelEditar.add(jButtonLimpiarE);
        jButtonLimpiarE.setBounds(340, 250, 130, 35);

        jButtonEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelEditar.add(jButtonEliminar);
        jButtonEliminar.setBounds(200, 250, 130, 35);

        jButtonActualizar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanelEditar.add(jButtonActualizar);
        jButtonActualizar.setBounds(60, 250, 130, 35);

        jTabbedPane1.addTab("Editar", jPanelEditar);

        jPanelRegistro.setLayout(null);

        jLabelRegistar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar.setText("Registar Estudiante");
        jPanelRegistro.add(jLabelRegistar);
        jLabelRegistar.setBounds(0, 10, 580, 40);

        jLCodigo.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLCodigo.setText("Codigo");
        jPanelRegistro.add(jLCodigo);
        jLCodigo.setBounds(50, 70, 200, 30);

        jLNombre.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLNombre.setText("Nombre");
        jPanelRegistro.add(jLNombre);
        jLNombre.setBounds(50, 110, 200, 30);

        jLSexo.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLSexo.setText("Sexo");
        jPanelRegistro.add(jLSexo);
        jLSexo.setBounds(50, 150, 200, 30);

        jLPrograma.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLPrograma.setText("Codigo Programa");
        jPanelRegistro.add(jLPrograma);
        jLPrograma.setBounds(50, 270, 200, 30);
        jPanelRegistro.add(txtId);
        txtId.setBounds(260, 70, 250, 30);
        jPanelRegistro.add(txtApellido);
        txtApellido.setBounds(260, 190, 250, 30);

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanelRegistro.add(jCBSexo);
        jCBSexo.setBounds(260, 150, 250, 30);

        jCBPrograma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jCBPrograma.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBProgramaPopupMenuWillBecomeVisible(evt);
            }
        });
        jPanelRegistro.add(jCBPrograma);
        jCBPrograma.setBounds(260, 270, 250, 30);

        jButtonLimpiarR.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonLimpiarR.setText("LIMPIAR");
        jButtonLimpiarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarRActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonLimpiarR);
        jButtonLimpiarR.setBounds(290, 350, 180, 35);

        jButtonRegistar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonRegistar.setText("REGISTAR");
        jButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonRegistar);
        jButtonRegistar.setBounds(100, 350, 170, 35);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Apellido");
        jPanelRegistro.add(jLabel2);
        jLabel2.setBounds(50, 190, 80, 30);
        jPanelRegistro.add(TxtNombre);
        TxtNombre.setBounds(260, 110, 250, 30);
        jPanelRegistro.add(txtFecha);
        txtFecha.setBounds(260, 230, 250, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nacimiento");
        jPanelRegistro.add(jLabel3);
        jLabel3.setBounds(50, 230, 180, 30);

        jTabbedPane1.addTab("Registar", jPanelRegistro);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Universidad Mariano 3.jpg"))); // NOI18N

        jButton1.setText("Estudiantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Programa Academico");

        jButton3.setText("Catedratico");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelRegistar2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRegistar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistar2.setText("Gestion Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegistar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabelRegistar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBPrograma1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBPrograma1PopupMenuWillBecomeVisible
        //<editor-fold defaultstate="collapsed" desc="jCBPrograma1PopupMenuWillBecomeVisible()">

        //</editor-fold>
    }//GEN-LAST:event_jCBPrograma1PopupMenuWillBecomeVisible

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Crear una instancia de FuncionesEstudiantes
        FuncionesEstudiantes funcionesEstudiantes = new FuncionesEstudiantes();

        // Obtener el id_estudiante desde algún componente de la interfaz (por ejemplo, un JTextField)
        int id_estudiante = Integer.parseInt(txtIdEstudiante.getText());

        // Llamar al método buscarEstudiantePorId y pasar el modelo de la tabla
        funcionesEstudiantes.buscarEstudiantePorId((DefaultTableModel) TablaResultados.getModel(), id_estudiante);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();
        FuncionesEstudiantes estudiantes = new FuncionesEstudiantes();
        // Obtener la fila seleccionada
        int filaSeleccionada = TablaResultados.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas en la fila seleccionada
            Object id = modelo.getValueAt(filaSeleccionada, 0);

            // Obtener los nuevos valores de los campos de texto y combobox
            String nuevoNombre = txtNombre.getText();
            String nuevoId = txtIdEstudiante.getText();
            String nuevoSexo = cmbSexo.getSelectedItem().toString();

            // Actualizar la información en la base de datos
            actualizarInformacionEstudiante(Integer.parseInt(id.toString()), nuevoNombre, nuevoId, nuevoSexo);

            // Limpiar la tabla y volver a cargar los datos
            estudiantes.limpiarTabla(modelo);
            // Vuelve a cargar todos los datos en la tabla (puedes llamar a tu método que carga los datos aquí)
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    private void actualizarInformacionEstudiante(int idEstudiante, String nuevoNombre, String nuevoId, String nuevoSexo) {
        Conexion db = new Conexion();

        try {
            Connection cn = db.getConnection();
            String consultaSQL = "UPDATE estudiantes SET nombre=?, id_estudiante=?, sexo=? WHERE id_estudiante=?";
            PreparedStatement pst = cn.prepareStatement(consultaSQL);

            pst.setString(1, nuevoNombre);
            pst.setString(2, nuevoId);
            pst.setString(3, nuevoSexo);
            pst.setInt(4, idEstudiante);

            int filasActualizadas = pst.executeUpdate();

            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(null, "Estudiante actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la información del estudiante.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar la información del estudiante: " + e);
        } finally {
            db.close(); // Cerrar la conexión al finalizar
        }
    }
    private void jCBPrograma3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBPrograma3PopupMenuWillBecomeVisible

    }//GEN-LAST:event_jCBPrograma3PopupMenuWillBecomeVisible

    private void jButtonLimpiarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarEActionPerformed

    }//GEN-LAST:event_jButtonLimpiarEActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed

    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarActionPerformed
        // Obtener los valores de los campos de texto y combobox
        String id = txtId.getText();
        String nombre = TxtNombre.getText();
        String apellido = txtApellido.getText();
        String sexo = cmbSexo.getSelectedItem().toString();
        String fechaNacimiento = txtFecha.getText();  // Asumiendo que txtFecha es un campo de texto para la fecha

        // Imprime los valores para depuración
        System.out.println("ID: " + id);
        System.out.println("Nombre: " + nombre);
        System.out.println("Apellido: " + apellido);
        System.out.println("Sexo: " + sexo);
        System.out.println("Fecha de Nacimiento: " + fechaNacimiento);

        // Guardar la información en la base de datos
        guardarEstudiante(id, nombre, apellido, sexo, fechaNacimiento);

        // Limpiar los campos después de guardar
        limpiarCampos();
    }//GEN-LAST:event_jButtonRegistarActionPerformed
    private void guardarEstudiante(String id, String nombre, String apellido, String sexo, String fechaNacimiento) {
        Conexion db = new Conexion();

        try {
            Connection cn = db.getConnection();
            String consultaSQL = "INSERT INTO estudiantes (id_estudiante, nombre, apellidos, sexo, fecha_nacimiento) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = cn.prepareStatement(consultaSQL);

            // Imprime los valores para depuración
            System.out.println("ID (en guardarEstudiante): " + id);
            System.out.println("Nombre (en guardarEstudiante): " + nombre);
            System.out.println("Apellido (en guardarEstudiante): " + apellido);
            System.out.println("Sexo (en guardarEstudiante): " + sexo);
            System.out.println("Fecha de Nacimiento (en guardarEstudiante): " + fechaNacimiento);

            pst.setString(1, id);
            pst.setString(2, nombre);
            pst.setString(3, apellido);
            pst.setString(4, sexo);
            pst.setString(5, fechaNacimiento);

            int filasInsertadas = pst.executeUpdate();

            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(null, "Estudiante registrado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el estudiante.");
            }
        } catch (SQLException e) {
            e.printStackTrace();  // Imprime la traza de la excepción para obtener más detalles en la consola
            JOptionPane.showMessageDialog(null, "Error al registrar el estudiante: " + e.getMessage());
        } finally {
            db.close(); // Cerrar la conexión al finalizar
        }
    }

    private void limpiarCampos() {
        // Limpiar los campos de texto y combobox
        txtId.setText("");
        TxtNombre.setText("");
        txtApellido.setText("");
        cmbSexo.setSelectedIndex(0);  // Puedes ajustar esto según la posición de las opciones en tu combobox
        txtFecha.setText("");
    }
    private void jButtonLimpiarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarRActionPerformed

    }//GEN-LAST:event_jButtonLimpiarRActionPerformed

    private void jCBProgramaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBProgramaPopupMenuWillBecomeVisible

    }//GEN-LAST:event_jCBProgramaPopupMenuWillBecomeVisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Crear una instancia de FuncionesEstudiantes
        FuncionesEstudiantes funcionesEstudiantes = new FuncionesEstudiantes();

        // Llamar al método limpiarTabla y pasar el modelo de la tabla
        funcionesEstudiantes.limpiarTabla((DefaultTableModel) TablaResultados.getModel());    }//GEN-LAST:event_jButton4ActionPerformed

    private void TablaResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaResultadosMouseClicked
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();

        // Obtener la fila seleccionada
        int filaSeleccionada = TablaResultados.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (filaSeleccionada != -1) {
            // Obtener los valores de las celdas en la fila seleccionada
            Object id = modelo.getValueAt(filaSeleccionada, 0);
            Object nombre = modelo.getValueAt(filaSeleccionada, 1);
            Object sexo = modelo.getValueAt(filaSeleccionada, 2);

            // Asignar los valores a los campos de texto y combobox
            txtIdEstudiante.setText(id.toString());
            txtNombre.setText(nombre.toString());
            cmbSexo.setSelectedItem(sexo.toString());
        }    }//GEN-LAST:event_TablaResultadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarReCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarReCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarReCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarReCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarReCon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaResultados;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonLimpiarE;
    private javax.swing.JButton jButtonLimpiarR;
    private javax.swing.JButton jButtonRegistar;
    private javax.swing.JComboBox jCBPrograma;
    private javax.swing.JComboBox jCBPrograma1;
    private javax.swing.JComboBox jCBPrograma3;
    private javax.swing.JComboBox jCBSexo;
    private javax.swing.JComboBox jCBSexo3;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLCodigo1;
    private javax.swing.JLabel jLCodigo3;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLNombre3;
    private javax.swing.JLabel jLPrograma;
    private javax.swing.JLabel jLPrograma1;
    private javax.swing.JLabel jLPrograma3;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLSexo1;
    private javax.swing.JLabel jLSexo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNotaEditar;
    private javax.swing.JLabel jLabelRegistar;
    private javax.swing.JLabel jLabelRegistar1;
    private javax.swing.JLabel jLabelRegistar2;
    private javax.swing.JLabel jLabelRegistar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo3;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEstudiante;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
